; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ====== Common Environment Configurations ======
[env]
framework = arduino
monitor_speed = 115200

; ====== Target 1: Pro Micro ======
[env:sparkfun_promicro16]
platform = atmelavr
board = sparkfun_promicro16
;board_build.f_cpu = 16000000L
build_unflags =
    -std=gnu++11
build_flags =
    -Os
    -flto
    -D__AVR_ATmega32U4__
    -D SERIAL_RX_BUFFER_SIZE=19
    -D SERIAL_TX_BUFFER_SIZE=4
    -I"${platformio.src_dir}"

; ====== Target 2: ATtiny3224 ======
[env:ATtiny3224]
platform = atmelmegaavr ; megaTinyCore?
board = ATtiny3224
board_build.f_cpu = 20000000L

build_flags =
    -Os
    -flto
    -D SERIAL_RX_BUFFER_SIZE=16
    -D SERIAL_TX_BUFFER_SIZE=16
;    -D HWSERIAL0_RX_BUFFER_SIZE=16
;    -D HWSERIAL0_TX_BUFFER_SIZE=4
;    -D HWSERIAL1_RX_BUFFER_SIZE=16
;    -D HWSERIAL1_TX_BUFFER_SIZE=4
    -I"${platformio.src_dir}"

upload_protocol = xplainedmini_updi
upload_flags =
    -b
    115200

[platformio]
# Set this to whichever example you are currently working on!
;src_dir = lib/MyOwnBricks/examples/ColorDistanceSensor
;src_dir = lib/MyOwnBricks/examples/ColorSensor
;src_dir = lib/MyOwnBricks/examples/EncoderMotor
;src_dir = lib/MyOwnBricks/examples/ForceSensor
;src_dir = lib/MyOwnBricks/examples/LightMatrix
src_dir = lib/MyOwnBricks/examples/TiltSensor
;src_dir = lib/MyOwnBricks/examples/UltrasonicSensor
;src_dir = src
